"""Pipeline Executor - Runs execution plans generated by COE.

This module executes ExecutionPlan objects by dispatching steps to appropriate
runners (python scripts, passthrough, agent calls) and managing artifact flow.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime
import importlib.util
import logging
from pathlib import Path
import sys
from typing import Any
import uuid

from dta.config import ROOT_DIR, TEMP_PATH
from dta.dti.coe.llm import LLMMessage, get_llm_router
from dta.dti.registry import get_item, load_registry
from dta.dti.schemas import ExecutionPlan, PlanStep, Registry, RegistryItem

logger = logging.getLogger(__name__)


class ExecutionError(Exception):
    """Raised when step execution fails."""


class MissingInputError(ExecutionError):
    """Raised when required input is missing.

    This is a recoverable error - the system can prompt the user
    to provide the missing input rather than failing completely.
    """

    def __init__(self, step_id: str, input_type: str, message: str | None = None) -> None:
        self.step_id = step_id
        self.input_type = input_type
        default_msg = f"Missing required input '{input_type}' for step '{step_id}'"
        super().__init__(message or default_msg)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            "error": "missing_input",
            "message": str(self),
            "step_id": self.step_id,
            "input_type": self.input_type,
        }


class CancellationError(Exception):
    """Raised when execution is cancelled."""


class ModelNotInstalledError(ExecutionError):
    """Raised when a required ML model is not installed.

    This error provides model info so the frontend can prompt
    the user to download the model.
    """

    def __init__(
        self,
        step_id: str,
        model_id: str,
        model_name: str,
        size_mb: int,
        description: str,
    ) -> None:
        self.step_id = step_id
        self.model_id = model_id
        self.model_name = model_name
        self.size_mb = size_mb
        self.description = description
        super().__init__(
            f"Model '{model_name}' ({size_mb} MB) is required but not installed. Please download it first."
        )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return {
            "error": "model_not_installed",
            "model_required": {
                "id": self.model_id,
                "name": self.model_name,
                "size_mb": self.size_mb,
                "description": self.description,
            },
            "message": f"This analysis requires the {self.model_name} model ({self.size_mb} MB). "
            f"Would you like to download it?",
        }


# Mapping from registry step IDs to model manager model IDs
STEP_TO_MODEL_MAP = {
    "models/prithvi-reconstruction": "prithvi-eo-v1-100m",
    "models/delineate-anything": "delineate-anything-small",
}


class PipelineExecutor:
    """Executes pipeline plans by dispatching steps to registered runners.

    The executor maintains an artifact dictionary that gets populated as steps
    execute. Each step can read from and write to this shared state.

    Example:
        >>> executor = PipelineExecutor()
        >>> plan = ExecutionPlan(steps=[...])
        >>> result = executor.execute(plan)
        >>> print(result["artifacts"])
    """

    def __init__(self, registry: Registry | None = None) -> None:
        """Initialize executor with optional registry.

        Args:
            registry: Component registry. If None, loads from default path.
        """
        self.registry = registry or load_registry()
        self.artifacts: dict[str, Any] = {}
        self.executed_items: list[RegistryItem] = []  # Track executed registry items for interpretation

    def execute(
        self,
        plan: ExecutionPlan,
        on_progress: Callable[[dict[str, Any]], None] | None = None,
        is_cancelled: Callable[[], bool] | None = None,
    ) -> dict[str, Any]:
        """Execute a pipeline plan step by step.

        Args:
            plan: Execution plan from COE planner
            on_progress: Optional callback for progress events
            is_cancelled: Optional callback to check if execution should be cancelled

        Returns:
            Dictionary with:
                - flow: Flow name
                - steps: List of executed step IDs
                - artifacts: All generated artifacts
                - outputs: Final output artifacts

        Raises:
            ExecutionError: If any step fails
            CancellationError: If execution is cancelled
        """
        self.artifacts = {}  # Reset for each execution
        self.executed_items = []  # Reset executed items
        executed_steps: list[str] = []

        for idx, step in enumerate(plan.steps, start=1):
            # Check for cancellation before each step
            if is_cancelled and is_cancelled():
                raise CancellationError("Execution cancelled by user")

            if on_progress:
                on_progress(
                    {
                        "event": "step_start",
                        "index": idx,
                        "total": len(plan.steps),
                        "step_id": step.uses,
                    }
                )

            try:
                item = get_item(self.registry, step.uses)
                self._execute_step(step, item)
                executed_steps.append(step.uses)
                self.executed_items.append(item)  # Track for interpretation lookup

                if on_progress:
                    on_progress(
                        {
                            "event": "step_complete",
                            "index": idx,
                            "total": len(plan.steps),
                            "step_id": step.uses,
                        }
                    )

            except Exception as e:
                if on_progress:
                    on_progress(
                        {
                            "event": "step_error",
                            "index": idx,
                            "step_id": step.uses,
                            "error": str(e),
                        }
                    )
                raise ExecutionError(f"Step {step.uses} failed: {e}") from e

        # Collect final outputs
        final_outputs = {}
        for output_key in plan.outputs:
            if ":" in output_key:  # e.g., "publish: chat"
                _, key = output_key.split(":", 1)
                key = key.strip()
                if key in self.artifacts:
                    final_outputs[key] = self.artifacts[key]
            elif output_key in self.artifacts:
                final_outputs[output_key] = self.artifacts[output_key]

        return {
            "flow": plan.flow,
            "steps": executed_steps,
            "artifacts": self.artifacts,
            "outputs": final_outputs,
        }

    def _execute_step(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute a single pipeline step.

        Args:
            step: Step configuration
            item: Registry item with runner config

        Raises:
            ExecutionError: If runner type is unknown or execution fails
            ModelNotInstalledError: If required model is not installed
        """
        # Check if this step requires an ML model
        self._check_model_availability(step, item)

        if item.runner is None:
            raise ExecutionError(f"Registry item {item.id} has no runner configured")
        runner_type = item.runner.type

        if runner_type == "passthrough":
            self._run_passthrough(step, item)
        elif runner_type == "python":
            self._run_python(step, item)
        elif runner_type == "agent":
            self._run_agent(step, item)
        else:
            raise ExecutionError(f"Unknown runner type: {runner_type}")

    def _check_model_availability(self, step: PlanStep, item: RegistryItem) -> None:
        """Check if required ML model is installed.

        Args:
            step: Step configuration
            item: Registry item

        Raises:
            ModelNotInstalledError: If model is not installed
        """
        # Check if this step uses a model that needs to be downloaded
        model_id = STEP_TO_MODEL_MAP.get(step.uses)
        if not model_id:
            return  # Not a model step, nothing to check

        from dta.dti.models import AVAILABLE_MODELS, get_model_manager

        manager = get_model_manager()

        if not manager.is_model_available(model_id):
            # Model not installed - raise error with model info
            model_info = AVAILABLE_MODELS.get(model_id)
            if model_info:
                raise ModelNotInstalledError(
                    step_id=step.uses,
                    model_id=model_id,
                    model_name=model_info.name,
                    size_mb=model_info.size_mb,
                    description=model_info.description,
                )

    def _run_passthrough(self, step: PlanStep, item: RegistryItem) -> None:
        """Handle passthrough runners (e.g., input/file).

        Passthrough simply forwards input values to outputs without processing.
        Useful for file inputs where the path is provided by the user.

        Args:
            step: Step configuration (may contain binds with values)
            item: Registry item

        Raises:
            ExecutionError: If required output has no binding
        """
        # For passthrough, binds in step contain the actual values
        # Example: step.binds = {"RasterPath": "/path/to/file.tif"}
        for output_type in item.outputs:
            if output_type in step.binds:
                self.artifacts[output_type] = step.binds[output_type]
            else:
                # Input steps require file bindings to work
                if step.uses.startswith("input/"):
                    raise MissingInputError(
                        step_id=step.uses,
                        input_type=output_type,
                        message=_get_friendly_missing_input_message(step.uses, output_type),
                    )
                # For other passthrough steps, mark as pending
                self.artifacts[output_type] = None

    def _run_python(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute Python entrypoint.

        Loads the Python module specified in item.runner.entrypoint and calls
        the specified function. Supports args_map for translating inputs.

        Args:
            step: Step configuration
            item: Registry item with entrypoint path

        Raises:
            ExecutionError: If entrypoint not found or execution fails
        """
        assert item.runner is not None  # checked by _execute_step
        if not item.runner.entrypoint:
            raise ExecutionError(f"Python runner {item.id} missing entrypoint")

        # Resolve ${MODEL_PATH} variable if this step has a model_id
        model_path: str | None = None
        model_id = STEP_TO_MODEL_MAP.get(step.uses)
        if model_id:
            from dta.dti.models import get_model_manager

            manager = get_model_manager()
            path = manager.get_model_path(model_id)
            if not path:
                raise ExecutionError(f"Model path not found for {model_id}")
            model_path = str(path)  # Convert Path to str for string operations

        # Collect inputs from artifacts first (needed for variable resolution)
        inputs: dict[str, Any] = {}
        for input_type in item.inputs:
            if input_type in self.artifacts:
                inputs[input_type] = self.artifacts[input_type]
            elif input_type in step.binds:
                # Support literal values passed in binds (e.g., IndexType="ndvi")
                # This allows planners to pass optional parameters directly
                inputs[input_type] = step.binds[input_type]

        # Create output directory for models
        output_dir: str | None = None
        if model_id:
            run_id = f"{model_id}_{datetime.utcnow().strftime('%Y%m%dT%H%M%S')}_{uuid.uuid4().hex[:8]}"
            output_dir_path = TEMP_PATH / f"{model_id}_outputs" / run_id
            output_dir_path.mkdir(parents=True, exist_ok=True)
            output_dir = str(output_dir_path)

        # Apply registry-defined preprocessors
        if item.preprocessors and output_dir:
            inputs = self._apply_preprocessors(item, inputs, output_dir)

        # Build variable context for resolution
        var_context = {
            "MODEL_PATH": model_path,
            "OUTPUT_DIR": output_dir,
            **inputs,  # Input types like RasterPath
        }

        # Resolve entrypoint - supports two forms:
        #   1. Dotted module path ("dta.dti.algorithms.ndvi") — bundled in-package
        #      code; loaded via importlib.import_module (cached, no sys.path mutation).
        #   2. Filesystem path ("dta/.../foo.py", "${MODEL_PATH}/inference.py") —
        #      third-party / runtime-resolved plugins; loaded via spec_from_file_location.
        entrypoint_str = self._resolve_variables(item.runner.entrypoint, var_context)
        is_filesystem_path = entrypoint_str.endswith(".py") or "/" in entrypoint_str or "\\" in entrypoint_str

        model_dir_added = False
        if is_filesystem_path:
            entrypoint = Path(entrypoint_str)
            if not entrypoint.is_absolute():
                entrypoint = ROOT_DIR / entrypoint
            if not entrypoint.exists():
                raise ExecutionError(f"Entrypoint not found: {entrypoint}")

            # Add the model directory to sys.path so the entrypoint can import
            # siblings (e.g. Prithvi's inference.py imports prithvi_mae.py).
            # Process-global mutation, but each model has a unique cache directory
            # and concurrent executions of the same model insert the same path —
            # so threads don't clobber each other in practice. Removing this would
            # require rewriting third-party model code to use relative imports.
            if model_path:
                model_dir = str(Path(model_path))
                if model_dir not in sys.path:
                    sys.path.insert(0, model_dir)
                    model_dir_added = True

            spec = importlib.util.spec_from_file_location(f"runner_{item.id.replace('/', '_')}", str(entrypoint))
            if spec is None or spec.loader is None:
                raise ExecutionError(f"Failed to load module: {entrypoint}")
            module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = module
            spec.loader.exec_module(module)
        else:
            try:
                module = importlib.import_module(entrypoint_str)
            except ImportError as e:
                raise ExecutionError(f"Failed to import module {entrypoint_str}: {e}") from e

        try:
            # Determine function to call and arguments
            if item.runner.args_map:
                # Use args_map - resolve all variables in the map
                func_args = self._resolve_args_map(item.runner.args_map, var_context)
                func_name = item.runner.function or "main"
                if not hasattr(module, func_name):
                    raise ExecutionError(f"Module {entrypoint_str} has no {func_name}() function")
                func = getattr(module, func_name)
                result = func(**func_args)
            else:
                # Simple mode: call run() or main() with collected inputs
                # Used for algorithms that don't require complex argument mapping
                if hasattr(module, "run"):
                    result = module.run(**inputs)
                elif hasattr(module, "main"):
                    result = module.main(**inputs)
                else:
                    raise ExecutionError(f"Module {entrypoint_str} has no run() or main()")

            # Store outputs
            if result is None and output_dir:
                # For models that don't return anything, create output from output_dir
                result = self._collect_model_outputs(model_id, output_dir, inputs)

            if len(item.outputs) == 1:
                self.artifacts[item.outputs[0]] = result
            elif isinstance(result, dict):
                for output_type in item.outputs:
                    if output_type in result:
                        self.artifacts[output_type] = result[output_type]
            else:
                raise ExecutionError(f"Cannot map result to outputs {item.outputs}. Expected dict or single output.")

        finally:
            # Remove model directory from sys.path. (No env restore needed —
            # algorithms now receive their config via runner.args_map kwargs,
            # never through process-global os.environ.)
            if model_dir_added and model_path:
                try:
                    sys.path.remove(str(Path(model_path)))
                except ValueError:
                    pass  # Already removed

    def _resolve_variables(self, value: str, context: dict[str, Any]) -> str:
        """Resolve ${VAR} placeholders in a string.

        Args:
            value: String with ${VAR} placeholders
            context: Variable name -> value mapping

        Returns:
            Resolved string
        """
        import re

        def replace(match: re.Match[str]) -> str:
            var_name = match.group(1)
            if var_name in context and context[var_name] is not None:
                return str(context[var_name])
            return match.group(0)  # Keep original if not found

        return str(re.sub(r"\$\{(\w+)\}", replace, value))

    def _resolve_args_map(self, args_map: dict[str, Any], context: dict[str, Any]) -> dict[str, Any]:
        """Resolve variables in args_map recursively.

        Args:
            args_map: Argument mapping with ${VAR} placeholders
            context: Variable name -> value mapping

        Returns:
            Resolved arguments dict
        """
        resolved = {}
        for key, value in args_map.items():
            resolved[key] = self._resolve_value(value, context)
        return resolved

    def _resolve_value(self, value: Any, context: dict[str, Any]) -> Any:
        """Resolve a single value, handling strings, lists, and dicts.

        Args:
            value: Value to resolve
            context: Variable context

        Returns:
            Resolved value
        """
        if isinstance(value, str):
            return self._resolve_variables(value, context)
        elif isinstance(value, list):
            return [self._resolve_value(v, context) for v in value]
        elif isinstance(value, dict):
            return {k: self._resolve_value(v, context) for k, v in value.items()}
        else:
            return value  # bools, ints, floats, None

    def _apply_preprocessors(self, item: RegistryItem, inputs: dict[str, Any], output_dir: str) -> dict[str, Any]:
        """Apply registry-defined preprocessors to inputs.

        Preprocessors are reusable data transformations defined in the registry.
        Each preprocessor specifies which input type it transforms.

        Args:
            item: Registry item with preprocessors defined
            inputs: Current input values
            output_dir: Directory for preprocessor outputs

        Returns:
            Updated inputs dict with preprocessed values
        """
        updated_inputs = inputs.copy()

        for preproc_ref in item.preprocessors:
            input_type = preproc_ref.apply_to
            if input_type not in updated_inputs:
                logger.debug(f"Preprocessor {preproc_ref.id}: input {input_type} not available, skipping")
                continue

            # Get preprocessor from registry
            preproc_item = get_item(self.registry, preproc_ref.id)
            if not preproc_item:
                logger.warning(f"Preprocessor not found in registry: {preproc_ref.id}")
                continue

            if not preproc_item.runner or not preproc_item.runner.entrypoint:
                logger.warning(f"Preprocessor {preproc_ref.id} has no runner/entrypoint")
                continue

            # Resolve and load preprocessor module
            entrypoint = Path(preproc_item.runner.entrypoint)
            if not entrypoint.is_absolute():
                entrypoint = ROOT_DIR / entrypoint

            if not entrypoint.exists():
                logger.warning(f"Preprocessor entrypoint not found: {entrypoint}")
                continue

            try:
                spec = importlib.util.spec_from_file_location(
                    f"preprocessor_{preproc_ref.id.replace('/', '_')}", str(entrypoint)
                )
                if spec is None or spec.loader is None:
                    raise ExecutionError(f"Failed to load preprocessor: {entrypoint}")

                module = importlib.util.module_from_spec(spec)
                sys.modules[spec.name] = module
                spec.loader.exec_module(module)

                # Call preprocessor function
                func_name = preproc_item.runner.function or "run"
                if not hasattr(module, func_name):
                    raise ExecutionError(f"Preprocessor {entrypoint} has no {func_name}() function")

                func = getattr(module, func_name)
                original_value = updated_inputs[input_type]
                new_value = func(input_path=original_value, output_dir=output_dir)

                updated_inputs[input_type] = new_value
                logger.info(f"Preprocessor {preproc_ref.id} applied to {input_type}: {original_value} -> {new_value}")

            except Exception as e:
                logger.warning(f"Preprocessor {preproc_ref.id} failed: {e}, using original value")
                continue

        return updated_inputs

    def _collect_model_outputs(self, model_id: str | None, output_dir: str, inputs: dict[str, Any]) -> dict[str, Any]:
        """Collect outputs from a model that writes to output_dir.

        Args:
            model_id: Model identifier
            output_dir: Directory where model wrote outputs
            inputs: Original inputs

        Returns:
            Output dictionary with visualizations for frontend display
        """
        output_path = Path(output_dir)
        output_files = list(output_path.glob("*.tiff")) + list(output_path.glob("*.tif"))

        result: dict[str, Any] = {
            "model": model_id or "unknown",
            "output_dir": output_dir,
            "output_files": [str(f) for f in output_files],
            "input_file": inputs.get("RasterPath"),
        }

        # Convert TIFF outputs to base64 PNG for frontend visualization
        visualizations = self._convert_tiffs_to_visualizations(output_files, model_id)
        if visualizations:
            result["visualizations"] = visualizations

        return result

    def _convert_tiffs_to_visualizations(self, tiff_files: list[Path], model_id: str | None) -> dict[str, str]:
        """Convert TIFF files to base64 PNG images for frontend display.

        Args:
            tiff_files: List of TIFF file paths
            model_id: Model identifier for labeling

        Returns:
            Dictionary mapping label -> base64 PNG string
        """
        import base64
        import io

        try:
            import numpy as np
            from PIL import Image
            import rasterio
        except ImportError:
            logger.warning("rasterio or PIL not available for TIFF conversion")
            return {}

        visualizations: dict[str, str] = {}

        for tiff_path in tiff_files:
            try:
                # Derive label from filename
                # e.g., "original_rgb_t0.tiff" -> "original_rgb_t0"
                label = tiff_path.stem

                with rasterio.open(tiff_path) as src:
                    # Read as RGB (first 3 bands or all if fewer)
                    bands = min(3, src.count)
                    data = src.read(list(range(1, bands + 1)))

                    # Handle different data types
                    if data.dtype == np.uint8:
                        # Already 8-bit, use directly
                        img_data = data
                    else:
                        # Normalize to 0-255 for other types
                        data_min = np.nanmin(data)
                        data_max = np.nanmax(data)
                        if data_max > data_min:
                            img_data = ((data - data_min) / (data_max - data_min) * 255).astype(np.uint8)
                        else:
                            img_data = np.zeros_like(data, dtype=np.uint8)

                    # Transpose from (C, H, W) to (H, W, C) for PIL
                    if img_data.shape[0] == 3:
                        img_array = np.transpose(img_data, (1, 2, 0))
                        img = Image.fromarray(img_array, mode="RGB")
                    elif img_data.shape[0] == 1:
                        img = Image.fromarray(img_data[0], mode="L")
                    else:
                        # Take first band as grayscale
                        img = Image.fromarray(img_data[0], mode="L")

                    # Convert to PNG base64
                    buffer = io.BytesIO()
                    img.save(buffer, format="PNG")
                    buffer.seek(0)
                    b64_str = base64.b64encode(buffer.read()).decode("utf-8")
                    visualizations[label] = b64_str

            except Exception as e:
                logger.warning(f"Failed to convert {tiff_path} to PNG: {e}")
                continue

        return visualizations

    def _run_agent(self, step: PlanStep, item: RegistryItem) -> None:
        """Execute agent runner (LLM-based processing).

        Agent runners invoke LLM for summarization, analysis, or other
        natural language processing tasks.

        Args:
            step: Step configuration
            item: Registry item

        Raises:
            ExecutionError: If agent execution fails
        """
        # Collect inputs
        # If agent has no specific inputs, pass all available artifacts
        inputs: dict[str, Any]
        if not item.inputs:
            inputs = dict(self.artifacts)  # Pass all artifacts to agent
        else:
            inputs = {}
            for input_type in item.inputs:
                if input_type in self.artifacts:
                    inputs[input_type] = self.artifacts[input_type]

        # Route to appropriate agent handler based on registry item
        if item.id == "post-processing/agent-analysis":
            result = self._agent_summarize(inputs)
            # Store in outputs
            if item.outputs:
                self.artifacts[item.outputs[0]] = result
            else:
                # Store as generic output
                self.artifacts["agent_result"] = result
        else:
            raise ExecutionError(f"Unknown agent type: {item.id}")

    def _agent_summarize(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Use LLM with agentic interpretation to summarize analysis results.

        The LLM can request additional analysis tools (metrics, statistics) when
        the available data is insufficient. This enables intelligent interpretation
        of visual outputs like reconstructions.

        Args:
            inputs: Dictionary of input artifacts

        Returns:
            Dictionary with summary text and any computed metrics
        """
        try:
            router = get_llm_router()

            # Determine analysis type from artifact keys
            analysis_type = self._detect_analysis_type(inputs)

            # Get domain-specific interpretation guide from registry
            interpretation_guide = self._get_interpretation_guide()

            # Build context description for LLM
            context_description = self._build_context_description(inputs)

            # Format any available statistics
            stats_context = self._format_stats_for_llm(inputs)

            # Determine if this is a visual-only output (no statistics)
            has_statistics = stats_context != "No statistics available."

            system_prompt = (
                "You are an expert geospatial analyst interpreting satellite imagery analysis results.\n\n"
                f"Domain knowledge:\n{interpretation_guide}\n\n"
                "OUTPUT FORMAT:\n"
                "- Write in plain text only (no markdown, no asterisks, no formatting)\n"
                "- Structure your response in 3-5 sentences with specific numbers\n"
                "- Be informative but concise\n\n"
                "TOOLS: You can request analysis tools by responding with a JSON block:\n"
                '```json\n{"tool": "tool_name", "args": {...}}\n```\n'
                "Available tools:\n"
                "- compute_image_similarity: Compare two images (args: image1_key, image2_key)\n"
                "- analyze_spatial_patterns: Analyze texture/edges in an image (args: image_key)"
            )

            # For visual outputs without statistics, encourage tool use
            if not has_statistics and "Visualizations" in context_description:
                user_prompt = (
                    f"Analysis type: {analysis_type}\n\n"
                    f"{context_description}\n\n"
                    "No statistics are available - only visualizations. "
                    "Use compute_image_similarity to compare original vs predicted images, "
                    "then provide interpretation based on the metrics."
                )
            else:
                user_prompt = (
                    f"Analysis type: {analysis_type}\n\n"
                    f"{context_description}\n\n"
                    f"{stats_context}\n\n"
                    "Provide your interpretation in plain text."
                )

            messages = [
                LLMMessage(role="system", content=system_prompt),
                LLMMessage(role="user", content=user_prompt),
            ]

            # Agentic loop: allow up to 2 tool calls
            computed_metrics: dict[str, Any] = {}
            max_iterations = 3
            final_response = None

            for _ in range(max_iterations):
                response = router.generate(messages, temperature=0.5)

                # Check if LLM requested a tool
                tool_request = self._parse_tool_request(response.text)

                if tool_request:
                    # Execute the requested tool
                    tool_result = self._execute_analysis_tool(tool_request, inputs)
                    computed_metrics[tool_request["tool"]] = tool_result

                    # Add tool result to conversation
                    messages.append(LLMMessage(role="assistant", content=response.text))
                    messages.append(
                        LLMMessage(
                            role="user",
                            content=f"Tool result:\n```json\n{self._format_tool_result(tool_result)}\n```\n\n"
                            "Now provide your interpretation based on all available data.",
                        )
                    )
                else:
                    # LLM provided final interpretation
                    final_response = response
                    break

            if final_response is None:
                final_response = response  # Use last response

            # Clean summary text - remove any residual tool request JSON
            summary_text = self._clean_summary_text(final_response.text)

            result = {
                "summary": summary_text,
                "inputs": inputs,
                "llm_provider": final_response.provider,
            }

            if computed_metrics:
                result["computed_metrics"] = computed_metrics

            return result

        except Exception as e:
            # Graceful degradation if all LLMs fail
            logger.exception("Agent summarization failed")
            return {
                "summary": f"Analysis complete. Results available but summarization failed: {e}",
                "inputs": inputs,
            }

    def _build_context_description(self, inputs: dict[str, Any]) -> str:
        """Build a description of available outputs for the LLM.

        Args:
            inputs: Dictionary of input artifacts

        Returns:
            Human-readable description of available data
        """
        lines = ["**Available outputs:**"]

        for key, value in inputs.items():
            if isinstance(value, dict):
                # Describe dict contents
                if "visualizations" in value:
                    viz_keys = list(value["visualizations"].keys())
                    lines.append(f"- {key}: Visualizations available: {viz_keys}")
                elif "output_files" in value:
                    files = [Path(f).name for f in value.get("output_files", [])]
                    lines.append(f"- {key}: Output files: {files}")
                elif "statistics" in value:
                    lines.append(f"- {key}: Contains statistics")
                else:
                    lines.append(f"- {key}: Dictionary with keys {list(value.keys())}")
            elif isinstance(value, str) and (value.endswith(".tif") or value.endswith(".tiff")):
                lines.append(f"- {key}: Raster file ({Path(value).name})")
            else:
                lines.append(f"- {key}: {type(value).__name__}")

        return "\n".join(lines)

    def _parse_tool_request(self, response_text: str) -> dict[str, Any] | None:
        """Parse a tool request from LLM response.

        Args:
            response_text: LLM response text

        Returns:
            Tool request dict or None if no tool requested
        """
        import json
        import re

        # Try 1: Look for JSON block with markdown code fence
        json_pattern = r"```json\s*(\{[^`]+\})\s*```"
        match = re.search(json_pattern, response_text, re.DOTALL)

        if match:
            try:
                request: dict[str, Any] = json.loads(match.group(1))
                if "tool" in request:
                    return request
            except json.JSONDecodeError:
                pass

        # Try 2: Look for raw JSON with "tool" key (no markdown wrapper)
        raw_json_pattern = r'\{"tool"\s*:\s*"[^"]+"\s*,\s*"args"\s*:\s*\{[^}]*\}\}'
        match = re.search(raw_json_pattern, response_text)

        if match:
            try:
                request = json.loads(match.group(0))
                if "tool" in request:
                    return request
            except json.JSONDecodeError:
                pass

        return None

    def _clean_summary_text(self, text: str) -> str:
        """Remove tool request JSON and clean up the summary text.

        Args:
            text: Raw LLM response text

        Returns:
            Cleaned text with tool requests removed
        """
        import re

        # Remove markdown-wrapped JSON blocks
        text = re.sub(r"```json\s*\{[^`]+\}\s*```", "", text, flags=re.DOTALL)

        # Remove raw JSON tool requests
        text = re.sub(r'\{"tool"\s*:\s*"[^"]+"\s*,\s*"args"\s*:\s*\{[^}]*\}\}', "", text)

        # Clean up extra whitespace
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = text.strip()

        return text

    def _execute_analysis_tool(self, tool_request: dict[str, Any], inputs: dict[str, Any]) -> dict[str, Any]:
        """Execute a requested analysis tool.

        Args:
            tool_request: Tool request with name and args
            inputs: Current artifacts for context

        Returns:
            Tool execution result
        """
        from dta.dti.post_processing.analysis_tools import execute_tool

        tool_name = tool_request.get("tool", "")
        args = tool_request.get("args", {})

        # Build context from inputs
        context: dict[str, Any] = {}

        # Extract visualizations and files from artifacts
        for value in inputs.values():
            if isinstance(value, dict):
                if "visualizations" in value:
                    context["visualizations"] = value["visualizations"]
                if "output_files" in value:
                    context["output_files"] = value["output_files"]

        return execute_tool(tool_name, args, context)

    def _format_tool_result(self, result: dict[str, Any]) -> str:
        """Format tool result as JSON string for LLM.

        Args:
            result: Tool result dictionary

        Returns:
            Formatted JSON string
        """
        import json

        # Format floats nicely
        def format_value(v: Any) -> Any:
            if isinstance(v, float):
                return round(v, 6)
            elif isinstance(v, dict):
                return {k: format_value(val) for k, val in v.items()}
            return v

        formatted = {k: format_value(v) for k, v in result.items()}
        return json.dumps(formatted, indent=2)

    def _get_interpretation_guide(self) -> str:
        """Get domain-specific interpretation guide from executed registry items.

        Looks up interpretation from registry items that produced the artifacts,
        falling back to a generic guide if none found.
        """
        # Collect interpretations from executed items (skip inputs/passthrough)
        interpretations = []
        for item in self.executed_items:
            if item.interpretation and item.kind in ("algorithm", "model"):
                interpretations.append(item.interpretation.strip())

        if interpretations:
            return "\n\n".join(interpretations)

        # Fallback for legacy or missing interpretations
        return "Interpret the statistics based on standard remote sensing analysis principles."

    def _format_stats_for_llm(self, inputs: dict[str, Any]) -> str:
        """Format statistics from inputs for LLM consumption.

        Handles nested artifact structure like {"NDVIMap": {"statistics": {...}}}
        """
        lines = []
        stats: dict[str, Any] = {}

        # Search for statistics in nested artifact structure
        # Inputs can be: {"NDVIMap": {"statistics": {...}}} or {"statistics": {...}}
        for artifact_value in inputs.values():
            if isinstance(artifact_value, dict):
                # Check if this artifact contains statistics
                if "statistics" in artifact_value:
                    nested_stats = artifact_value["statistics"]
                    if isinstance(nested_stats, dict):
                        stats.update(nested_stats)
                # Also check for Statistics (capitalized)
                if "Statistics" in artifact_value:
                    nested_stats = artifact_value["Statistics"]
                    if isinstance(nested_stats, dict):
                        stats.update(nested_stats)

        # Also check top-level statistics
        if "statistics" in inputs and isinstance(inputs["statistics"], dict):
            stats.update(inputs["statistics"])
        if "Statistics" in inputs and isinstance(inputs["Statistics"], dict):
            stats.update(inputs["Statistics"])

        if stats:
            lines.append("**Statistics:**")
            for stat_key, stat_value in stats.items():
                if isinstance(stat_value, dict):
                    continue  # Skip nested dicts
                if isinstance(stat_value, float):
                    lines.append(f"- {stat_key}: {stat_value:.4f}")
                elif isinstance(stat_value, int):
                    lines.append(f"- {stat_key}: {stat_value:,}")
                else:
                    lines.append(f"- {stat_key}: {stat_value}")

        return "\n".join(lines) if lines else "No statistics available."

    def _detect_analysis_type(self, inputs: dict[str, Any]) -> str:
        """Detect the type of analysis from artifact keys.

        Args:
            inputs: Dictionary of input artifacts

        Returns:
            Human-readable analysis type description
        """
        keys = set(inputs.keys())

        # Check for specific analysis markers
        if "ndvi_array" in keys or "NDVIMap" in keys:
            return "NDVI (Normalized Difference Vegetation Index)"
        if "NDSIMap" in keys or "ndsi_array" in keys:
            return "NDSI (Normalized Difference Snow Index)"
        if "SnowClassification" in keys or "snow_mask" in keys:
            return "Snow Classification"
        if "change_array" in keys or "ChangeMap" in keys:
            return "change detection"
        if "FieldBoundaries" in keys or "boundaries" in keys:
            return "field boundary detection"
        if "Features" in keys or "embeddings" in keys:
            return "Prithvi feature extraction"
        if "Reconstruction" in keys:
            return "Prithvi reconstruction"
        if "Statistics" in keys or "statistics" in keys:
            return "raster statistics"

        # Generic fallback
        return "geospatial"


def _get_friendly_missing_input_message(step_id: str, input_type: str) -> str:
    """Generate a user-friendly message for missing input.

    Args:
        step_id: The step that needs the input (e.g., "input/file")
        input_type: The type of input needed (e.g., "RasterPath")

    Returns:
        User-friendly error message with guidance
    """
    messages = {
        "input/file": ("I need a file to process this request. Please upload a GeoTIFF image and try again."),
        "input/file-before": (
            "I need a 'before' image for change detection. Please upload the earlier date GeoTIFF image."
        ),
        "input/file-after": (
            "I need an 'after' image for change detection. Please upload the later date GeoTIFF image."
        ),
    }

    if step_id in messages:
        return messages[step_id]

    # Fallback based on input type
    if "Raster" in input_type or "Path" in input_type:
        return (
            f"I need a file to continue. Please upload a GeoTIFF image for the {step_id.replace('input/', '')} input."
        )

    return f"Missing required input for {step_id}. Please provide the necessary data and try again."
